## This Dockerfile is auto-generated by scripts/buildDockerfile.ts

FROM node:22-alpine as builder

RUN apk update && apk upgrade

WORKDIR /app-build
COPY .dev.mk .
COPY bin ./bin
COPY package.json .
COPY package-lock.json .
COPY rollup.config.mjs .
COPY tsconfig.json .
COPY scripts ./scripts
COPY src ./src
COPY static ./static
RUN npm ci && NODE_ENV=production node_modules/.bin/rollup -c && npm pack && mv *.tgz /tmp/app.tgz

WORKDIR /app
RUN npm install --no-optional --no-package-lock /tmp/app.tgz && rm -f /tmp/app.tgz && rm -rf /app-build && npm cache clean --force

ENV NODE_ENV=production \
 DM_PORT="8081" \
 DM_PLUGINS=core/static,core/helloworld \
 DM_LOG_LEVEL="info" \
 DM_LOGGER="console" \
 DM_API_PREFIX="/api" \
 DM_MAIL_DOMAIN= \
 DM_LDAP_BASE= \
 DM_LDAP_DN="cn=admin,dc=example,dc=com" \
 DM_LDAP_PWD="admin" \
 DM_LDAP_URL="ldap://localhost" \
 DM_LDAP_USER_ATTRIBUTE="uid" \
 DM_SCHEMAS_PATH="/app/node_modules/mini-dm/static/schemas" \
 DM_MAIL_ATTRIBUTE="mail" \
 DM_QUOTA_ATTRIBUTE="mailQuota" \
 DM_USER_CLASSES=top,twakeAccount,twakeWhitePages \
 DM_LDAP_TOP_ORGANIZATION= \
 DM_LDAP_ORGANIZATION_CLASSES=top,organizationalUnit,twakeDepartment \
 DM_LDAP_ORGANIZATION_LINK_ATTRIBUTE="twakeDepartmentLink" \
 DM_LDAP_ORGANIZATION_PATH_ATTRIBUTE="twakeDepartmentPath" \
 DM_LDAP_ORGANIZATION_PATH_SEPARATOR=" / " \
 DM_LDAP_ORGANIZATION_MAX_SUBNODES="50" \
 DM_LDAP_GROUP_BASE= \
 DM_LDAP_GROUPS_MAIN_ATTRIBUTE="cn" \
 DM_GROUP_CLASSES=top,groupOfNames \
 DM_ALLOW_UNEXISTENT_MEMBERS=false \
 DM_GROUP_DEFAULT_ATTRIBUTES="{}" \
 DM_GROUP_DUMMY_USER="cn=fakeuser" \
 DM_GROUP_SCHEMA="/app/node_modules/mini-dm/static/schemas/twake/groups.json" \
 DM_EXTERNAL_MEMBERS_BRANCH="ou=contacts,dc=example,dc=com" \
 DM_EXTERNAL_BRANCH_CLASSES=top,inetOrgPerson \
 DM_STATIC_PATH="/app/node_modules/mini-dm/static" \
 DM_STATIC_NAME="static" \
 DM_LDAP_FLAT_SCHEMA= \
 DM_JAMES_WEBADMIN_URL="http://localhost:8000" \
 DM_JAMES_WEBADMIN_TOKEN= \
 DM_CALENDAR_WEBADMIN_URL="http://localhost:8080" \
 DM_CALENDAR_WEBADMIN_TOKEN= \
 DM_CALENDAR_RESOURCE_BASE= \
 DM_CALENDAR_RESOURCE_OBJECTCLASS= \
 DM_CALENDAR_RESOURCE_CREATOR= \
 DM_CALENDAR_RESOURCE_DOMAIN= \
 DM_LLNG_INI="/etc/lemonldap-ng/lemonldap-ng.ini" \
 DM_AUTH_TOKENS= \
 DM_AUTHN_PER_BRANCH_CONFIG="{\"default\":{\"read\":true,\"write\":false,\"delete\":false}}" \
 DM_AUTHN_PER_BRANCH_CACHE_TTL="60" \
 DM_OIDC_SERVER= \
 DM_OIDC_CLIENT_ID= \
 DM_OIDC_CLIENT_SECRET= \
 DM_BASE_URL= \
 DM_RATE_LIMIT_WINDOW_MS="900000" \
 DM_RATE_LIMIT_MAX="100" \
 DM_CROWDSEC_URL="http://localhost:8080/v1/decisions" \
 DM_CROWDSEC_API_KEY= \
 DM_CROWDSEC_CACHE_TTL="60"

EXPOSE 8081
CMD ["npx", "mini-dm"]
